title: Harish Babu's Personal Portfolio
logo: assets/img/highres-logo-transparent.png
description: Here resides all the pages of Harish's portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
